# Generated by Django 3.2.9 on 2021-12-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_calculation_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ('created_at',), 'verbose_name': 'calculation', 'verbose_name_plural': 'calculations'},
        ),
    ]
